---
server:
  port: 8080
  host_port: localhost:8080
  #log_path: logrus.log

nats:
  #url: "localhost:4222" #for local
  url: "nats://nats:4222" #for docker
  name: "EVENTS"
  #subjects: "events" # subjects: "events.>"
  subjects.topic: "events.users_info"
...